[project]
name = "anki-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anki~=25.2",
    "beautifulsoup4~=4.13",
    "rich~=13.6",
    "typer~=0.15",
]
